### ISSUE TITLE
Discord -> Minecraft handling

### ISSUE THREAD

**Issue by Vankka** [DiscordSRV/Iris#3]
- [ ] DiscordSRV v1 options [(config)](https://github.com/DiscordSRV/DiscordSRV/blob/75d61bc51d522e2b85320253dfc60bac0586d2d2/src/main/resources/config/en.yml#L170-L173)
- [ ] DiscordSRV v1 options [(messages)](https://github.com/DiscordSRV/DiscordSRV/blob/75d61bc51d522e2b85320253dfc60bac0586d2d2/src/main/resources/messages/en.yml#L24-L26)
- [x] Kyori components (https://github.com/KyoriPowered/text)
  + [ ] Support JSON messages where possible (https://github.com/DiscordSRV/DiscordSRV/issues/319)
      - [ ] Hover text with placeholders such as linked account name (Suggested by a user on [SpigotMC](https://www.spigotmc.org/threads/discordsrv.123540/page-60#post-3609304))
- [ ] MCDiscordReserializer (https://github.com/Vankka/MCDiscordReserializer)
  + content must not have escaped formatting codes, eg. * _ ~
  +   + ability to limit who can use it (escape codes otherwise)
- [ ] Per channel configuration (formats) https://github.com/DiscordSRV/DiscordSRV/issues/323 
  + Configuring more things than just the format per channel would make more advanced configurations possible
- [ ] Filtering message content https://github.com/DiscordSRV/DiscordSRV/issues/258
- [ ] Disabling (all) mentions (maybe disabling the individually?)
- [ ] Placeholders
  + ChannelColor https://github.com/DiscordSRV/DiscordSRV/issues/358
  + TopRoleInitial https://github.com/DiscordSRV/DiscordSRV/issues/333
